### PR TITLE
Migrated to PCL (Profile 78) 

### PR DESCRIPTION
**Pull request by alexshikov**
Supports Xamarin.iOS and Xamarin.Android portable projects.

### CODE REVIEW

**Comment by alexshikov** [comment]
@vegardlarsen done

**Comment by vegardlarsen** [comment]
I'm having a little trouble getting this to build with this profile, since I don't have Xamarin installed. I'm headed to Build on Monday (and will be gone for a good week afterwards), so it will be a while before I can push a new Nuget package. Sorry.

Otherwise, this looks good. I had a bit of a reaction to removing async/await from methods who only call one async method, but apparently there is nothing wrong with that.

**Comment by vegardlarsen** [comment]
I figured out how to get it to build after a bit of tinkering. Updated version will be on nuget shortly.

**Comment by alexshikov** [comment]
What build issue have you had and how did you solve it? Have you installed Xamarin? (it would help in case I'll modify other libraries, that initially are not planned for PCL)

As for async/await I've recently realised that single await/async adds extra code in DLL's and decided to remove it if possible (hope I'm not wrong about this behaviour, because I'm deleting such code everywhere - and it would be sad, if compiler do this job instead :) )

**Comment by vegardlarsen** [comment]
It was one of the NuGet packages that was missing. Uninstalling and reinstalling it changed `packages.config` to not include the correct `targetFramework`. Reverting that change, and then rebuilding seemed to fix it.

From what I can understand about the async/await issue, it may have been wrong of me to accept this, but opinions go different ways. I think I may have to revert those changes at some point, because it seems that there are things that can go wrong, specifically with exception propagation. The example in the [top answer here](http://stackoverflow.com/questions/21033150/any-difference-between-await-task-run-return-and-return-task-run) does a good job of explaining what is wrong with it.

**Pull request merged**
